joints:
  - fl_flipper_joint
  - fr_flipper_joint
  - rl_flipper_joint
  - rr_flipper_joint
collision_links:
  # Main tracks
  - link: left_track
    type: track
    include_indices: [0, 1]
    cylinder_angle_min: -1.57
    cylinder_angle_max: 1.57
    resolution: &track_resolution 0.075
  - link: left_track
    type: track
    include_indices: [2]
    cylinder_angle_min: 2.617
    cylinder_angle_max: 4.7115
    resolution: *track_resolution

  - link: right_track
    type: track
    include_indices: [0, 1]
    cylinder_angle_min: -1.57
    cylinder_angle_max: 1.57
    resolution: *track_resolution
  - link: right_track
    type: track
    include_indices: [2]
    cylinder_angle_min: 2.617
    cylinder_angle_max: 4.7115
    resolution: *track_resolution
  # Wheels
  #- link: left_sprocket
    #type: track
    #resolution: &wheel_resolution 0.045
    #cylinder_angle_min: &sprocket_angle_min -1.2
    #cylinder_angle_max: &sprocket_angle_max 2.2
  #- link: right_sprocket
    #type: track
    #resolution: *wheel_resolution
    #cylinder_angle_min: *sprocket_angle_min
    #cylinder_angle_max: *sprocket_angle_max
  #- link: left_idler
    #type: track
    #resolution: *wheel_resolution
    #cylinder_angle_min: &idler_angle_min 2.3
    #cylinder_angle_max: &idler_angle_max 4.8
  #- link: right_idler
    #type: track
    #cylinder_angle_min: *idler_angle_min
    #cylinder_angle_max: *idler_angle_max
    #resolution: *wheel_resolution

  # Flippers
  - link: fl_track
    type: track
    resolution: &flipper_resolution 0.05
    include_indices: [0, 1]
    cylinder_angle_min: -1.57
    cylinder_angle_max: 1.8
  - link: fl_track
    type: track
    resolution: *flipper_resolution
    include_indices: [2]
    cylinder_angle_min: -3.1415
    cylinder_angle_max: -1.57

  - link: fr_track
    type: track
    resolution: *flipper_resolution
    include_indices: [0, 1]
    cylinder_angle_min: -1.57
    cylinder_angle_max: 1.8
  - link: fr_track
    type: track
    resolution: *flipper_resolution
    include_indices: [2]
    cylinder_angle_min: -3.1415
    cylinder_angle_max: -1.57

  - link: rl_track
    type: track
    resolution: *flipper_resolution
    include_indices: [0, 1]
    cylinder_angle_min: -1.57
    cylinder_angle_max: 1.8
  - link: rl_track
    type: track
    resolution: *flipper_resolution
    include_indices: [2]
    cylinder_angle_min: -3.1415
    cylinder_angle_max: -1.57

  - link: rr_track
    type: track
    resolution: *flipper_resolution
    include_indices: [0, 1]
    cylinder_angle_min: -1.57
    cylinder_angle_max: 1.8
  - link: rr_track
    type: track
    resolution: *flipper_resolution
    include_indices: [2]
    cylinder_angle_min: -3.1415
    cylinder_angle_max: -1.57


